// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDPigkzF6AOYTakDF0SwCijUFP4SezZcXU',
    appId: '1:170728018118:web:9c35b37e9ccf67b1ec87c7',
    messagingSenderId: '170728018118',
    projectId: 'flicky-df285',
    authDomain: 'flicky-df285.firebaseapp.com',
    storageBucket: 'flicky-df285.firebasestorage.app',
    measurementId: 'G-J88GFNVSY1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCUXCfKcSpRjujmormlFdOn1QAC0TvSQgI',
    appId: '1:170728018118:android:35c230f2b494346fec87c7',
    messagingSenderId: '170728018118',
    projectId: 'flicky-df285',
    storageBucket: 'flicky-df285.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD3jOjLHLZZllHags9k24IE8ppX0EUNYnM',
    appId: '1:170728018118:ios:e24894c31065eb30ec87c7',
    messagingSenderId: '170728018118',
    projectId: 'flicky-df285',
    storageBucket: 'flicky-df285.firebasestorage.app',
    iosBundleId: 'com.example.flicky',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD3jOjLHLZZllHags9k24IE8ppX0EUNYnM',
    appId: '1:170728018118:ios:e24894c31065eb30ec87c7',
    messagingSenderId: '170728018118',
    projectId: 'flicky-df285',
    storageBucket: 'flicky-df285.firebasestorage.app',
    iosBundleId: 'com.example.flicky',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDPigkzF6AOYTakDF0SwCijUFP4SezZcXU',
    appId: '1:170728018118:web:53f96d748ca8c0e6ec87c7',
    messagingSenderId: '170728018118',
    projectId: 'flicky-df285',
    authDomain: 'flicky-df285.firebaseapp.com',
    storageBucket: 'flicky-df285.firebasestorage.app',
    measurementId: 'G-8XV0Z3E093',
  );
}
